#!/bin/bash

if ! type cmus >/dev/null 2>&1; then
  echo "cmus is not installed!"
  exit 1
else
  CMUSQ=$(cmus-remote -Q 2>/dev/null)
  if [[ -z "$CMUSQ" ]]; then
    echo "cmus is not running!"
    exit 1
  else
    ARTIST=$(cmus-remote -Q 2>/dev/null | grep -m 1 'artist' | cut -d " " -f 3-)
    TITLE=$(cmus-remote -Q 2>/dev/null | grep -m 1 'title' | cut -d " " -f 3-)
    ALBUM=$(cmus-remote -Q 2>/dev/null | grep -m 1 'album' | cut -d " " -f 3-)
    if [[ -z "$ARTIST" ]]; then
      echo "cmus is not playing anything!"
    else
      title=$(echo "$TITLE" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
      artist=$(echo "$ARTIST" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
      lyrics_file="$HOME/Lyrics/$ARTIST - $ALBUM - $TITLE"
      lyrics_not_found="Sorry, We don't have lyrics for this song yet."
      
      if [ ! -f "$lyrics_file" ]; then
        wget "http://makeitpersonal.co/lyrics?artist=$artist&title=$title" -O "$lyrics_file" -T 30 >/dev/null 2>&1
      fi
      
      if grep -q "$lyrics_not_found" "$lyrics_file"; then
        rm -f "$lyrics_file"
        echo "duh, they don't have the lyrics for this song :/"
      else
        printf "*** $TITLE by $ARTIST from $ALBUM ***\n"|cat - "$lyrics_file" | less
      fi
    fi
  fi
fi

exit 0
